"""Add indexes to Message.chat

Revision ID: 50910865b768
Revises: 7b417973445f
Create Date: 2017-01-16 00:38:42.917681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50910865b768'
down_revision = '7b417973445f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_chat'), 'message', ['chat'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_chat'), table_name='message')
    # ### end Alembic commands ###
