"""Change name to login

Revision ID: 7940bc172ad5
Revises: a39f1fb11a75
Create Date: 2017-01-12 14:45:03.129524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7940bc172ad5'
down_revision = 'a39f1fb11a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=False)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
