"""Add unique index to User.login

Revision ID: a6ccff159e51
Revises: 50910865b768
Create Date: 2017-01-16 16:43:35.122319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ccff159e51'
down_revision = '50910865b768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_login', table_name='user')
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_login', 'user', ['login'], unique=False)
    # ### end Alembic commands ###
